source "https://rubygems.org"

gem "activesupport"
gem "andyw8-seeing_is_believing"
gem "m"
gem "minitest"
gem "minitest-reporters"
gem "mocha"
gem "debug", ">= 1.6.0"
gem "rake"
gem "ruby-lsp"
gem "rubocop-minitest"
gem "solargraph"
gem "standard"
